create_clock -period 20.000 -name SYSCLK -waveform {0.000 10.000} [get_ports SYSCLK]
set_property PACKAGE_PIN G4 [get_ports SYSCLK]
set_property IOSTANDARD LVCMOS33 [get_ports SYSCLK]
set_property IOSTANDARD LVCMOS33 [get_ports {IOx[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOx[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOx[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOx[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOx[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOx[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOx[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IOx[0]}]
set_property PACKAGE_PIN L1 [get_ports {IOx[7]}]
set_property PACKAGE_PIN L2 [get_ports {IOx[6]}]
set_property PACKAGE_PIN L3 [get_ports {IOx[5]}]
set_property PACKAGE_PIN M1 [get_ports {IOx[4]}]
set_property PACKAGE_PIN M2 [get_ports {IOx[3]}]
set_property PACKAGE_PIN M3 [get_ports {IOx[2]}]
set_property PACKAGE_PIN M4 [get_ports {IOx[1]}]
set_property PACKAGE_PIN M5 [get_ports {IOx[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LatchIOBank[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LatchIOBank[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nAB[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nAB[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nAB[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nAB[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nAB[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nAB[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nAB[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nAB[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nAB[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nAB[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nAB[1]}]
set_property PACKAGE_PIN P13 [get_ports {nAB[1]}]
set_property PACKAGE_PIN P12 [get_ports {nAB[2]}]
set_property PACKAGE_PIN P11 [get_ports {nAB[3]}]
set_property PACKAGE_PIN P10 [get_ports {nAB[4]}]
set_property PACKAGE_PIN N11 [get_ports {nAB[5]}]
set_property PACKAGE_PIN N10 [get_ports {nAB[6]}]
set_property PACKAGE_PIN M12 [get_ports {nAB[7]}]
set_property PACKAGE_PIN M11 [get_ports {nAB[8]}]
set_property PACKAGE_PIN H14 [get_ports {nAB[9]}]
set_property PACKAGE_PIN H13 [get_ports {nAB[10]}]
set_property PACKAGE_PIN H12 [get_ports {nAB[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nDO[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nDO[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nDO[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nDO[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nDO[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nDO[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nDO[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nDO[1]}]
set_property PACKAGE_PIN P3 [get_ports {nDO[8]}]
set_property PACKAGE_PIN P4 [get_ports {nDO[7]}]
set_property PACKAGE_PIN C5 [get_ports {nDO[6]}]
set_property PACKAGE_PIN C4 [get_ports {nDO[5]}]
set_property PACKAGE_PIN B2 [get_ports {nDO[4]}]
set_property PACKAGE_PIN B1 [get_ports {nDO[3]}]
set_property PACKAGE_PIN A4 [get_ports {nDO[2]}]
set_property PACKAGE_PIN A3 [get_ports {nDO[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nID[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nID[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nID[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nID[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nID[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nID[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nID[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {nID[1]}]
set_property PACKAGE_PIN H4 [get_ports {nID[8]}]
set_property PACKAGE_PIN H3 [get_ports {nID[7]}]
set_property PACKAGE_PIN H2 [get_ports {nID[6]}]
set_property PACKAGE_PIN H1 [get_ports {nID[5]}]
set_property PACKAGE_PIN F14 [get_ports {nID[1]}]
set_property PACKAGE_PIN F13 [get_ports {nID[2]}]
set_property PACKAGE_PIN F12 [get_ports {nID[3]}]
set_property PACKAGE_PIN F11 [get_ports {nID[4]}]
set_property PACKAGE_PIN F2 [get_ports CKA]
set_property IOSTANDARD LVCMOS33 [get_ports CKA]
set_property PACKAGE_PIN F3 [get_ports nCKB]
set_property IOSTANDARD LVCMOS33 [get_ports nCKB]
set_property PACKAGE_PIN B3 [get_ports VS0]
set_property PACKAGE_PIN B5 [get_ports VS1]
set_property PACKAGE_PIN B6 [get_ports VS2]
set_property IOSTANDARD LVCMOS33 [get_ports VS0]
set_property IOSTANDARD LVCMOS33 [get_ports VS1]
set_property IOSTANDARD LVCMOS33 [get_ports VS2]
set_property PACKAGE_PIN A13 [get_ports TXp]
set_property IOSTANDARD LVCMOS33 [get_ports TXp]
set_property PACKAGE_PIN A12 [get_ports RXp]
set_property IOSTANDARD LVCMOS33 [get_ports RXp]
set_property PACKAGE_PIN D13 [get_ports SPO]
set_property IOSTANDARD LVCMOS33 [get_ports SPO]
set_property PACKAGE_PIN D14 [get_ports nW_IO]
set_property IOSTANDARD LVCMOS33 [get_ports nW_IO]
set_property PACKAGE_PIN H11 [get_ports nRRSEL]
set_property IOSTANDARD LVCMOS33 [get_ports nRRSEL]
set_property PACKAGE_PIN K3 [get_ports {SelIOBank[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SelIOBank[0]}]
set_property PACKAGE_PIN K4 [get_ports {SelIOBank[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SelIOBank[1]}]
set_property PACKAGE_PIN A5 [get_ports {LatchIOBank[0]}]
set_property PACKAGE_PIN A2 [get_ports {LatchIOBank[1]}]
set_property PACKAGE_PIN J3 [get_ports SELIODir]
set_property IOSTANDARD LVCMOS33 [get_ports SELIODir]
set_property PACKAGE_PIN D4 [get_ports SetDDirL]
set_property IOSTANDARD LVCMOS33 [get_ports SetDDirL]
set_property PACKAGE_PIN J2 [get_ports SetDDirH]
set_property IOSTANDARD LVCMOS33 [get_ports SetDDirH]

set_property PACKAGE_PIN D1 [get_ports OPTIN3_33]
set_property IOSTANDARD LVCMOS33 [get_ports OPTIN3_33]
set_property DRIVE 8 [get_ports OPTIN3_33]

set_property PACKAGE_PIN D2 [get_ports OUT_OPT2]
set_property IOSTANDARD LVCMOS33 [get_ports OUT_OPT2]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]

set_property PULLTYPE PULLDOWN [get_ports SPO]

set_property DRIVE 4 [get_ports {LatchIOBank[1]}]
set_property DRIVE 4 [get_ports {LatchIOBank[0]}]
set_property DRIVE 4 [get_ports {IOx[7]}]
set_property DRIVE 4 [get_ports {IOx[6]}]
set_property DRIVE 4 [get_ports {IOx[5]}]
set_property DRIVE 4 [get_ports {IOx[4]}]
set_property DRIVE 4 [get_ports {IOx[3]}]
set_property DRIVE 4 [get_ports {IOx[2]}]
set_property DRIVE 4 [get_ports {IOx[1]}]
set_property DRIVE 4 [get_ports {IOx[0]}]
set_property DRIVE 4 [get_ports {nDO[8]}]
set_property DRIVE 4 [get_ports {nDO[7]}]
set_property DRIVE 4 [get_ports {nDO[6]}]
set_property DRIVE 4 [get_ports {nDO[5]}]
set_property DRIVE 4 [get_ports {nDO[4]}]
set_property DRIVE 4 [get_ports {nDO[3]}]
set_property DRIVE 4 [get_ports {nDO[2]}]
set_property DRIVE 4 [get_ports {nDO[1]}]
set_property DRIVE 4 [get_ports {SelIOBank[1]}]
set_property DRIVE 4 [get_ports {SelIOBank[0]}]
set_property DRIVE 4 [get_ports VS2]
set_property DRIVE 4 [get_ports SetDDirH]
set_property DRIVE 4 [get_ports SetDDirL]
set_property DRIVE 4 [get_ports VS1]
set_property DRIVE 4 [get_ports VS0]
set_property DRIVE 4 [get_ports TXp]
set_property DRIVE 4 [get_ports SELIODir]
set_property DRIVE 4 [get_ports OUT_OPT2]

set_property SLEW SLOW [get_ports {IOx[7]}]
set_property SLEW SLOW [get_ports {IOx[6]}]
set_property SLEW SLOW [get_ports {IOx[5]}]
set_property SLEW SLOW [get_ports {IOx[4]}]
set_property SLEW SLOW [get_ports {IOx[3]}]
set_property SLEW SLOW [get_ports {IOx[2]}]
set_property SLEW SLOW [get_ports {IOx[1]}]
set_property SLEW SLOW [get_ports {IOx[0]}]


set_property CFGBVS VCCO [current_design]

set_property CONFIG_VOLTAGE 3.3 [current_design]


set_property PULLTYPE PULLUP [get_ports {IOx[7]}]
set_property PULLTYPE PULLUP [get_ports {IOx[6]}]
set_property PULLTYPE PULLUP [get_ports {IOx[5]}]
set_property PULLTYPE PULLUP [get_ports {IOx[4]}]
set_property PULLTYPE PULLUP [get_ports {IOx[3]}]
set_property PULLTYPE PULLUP [get_ports {IOx[2]}]
set_property PULLTYPE PULLUP [get_ports {IOx[1]}]
set_property PULLTYPE PULLUP [get_ports {IOx[0]}]

set_property PULLTYPE PULLUP [get_ports SELIODir]

set_property BITSTREAM.CONFIG.CONFIGRATE 26 [current_design]

set_property BITSTREAM.CONFIG.USERID 32'hA1761B1D [current_design]
set_property BITSTREAM.STARTUP.STARTUPCLK CCLK [current_design]


set_operating_conditions -heatsink none

set_property IOSTANDARD LVCMOS33 [get_ports SCL]
set_property IOSTANDARD LVCMOS33 [get_ports SDA]
set_property PACKAGE_PIN B13 [get_ports SCL]
set_property PACKAGE_PIN B14 [get_ports SDA]
set_property DRIVE 4 [get_ports SCL]
set_property DRIVE 4 [get_ports SDA]
set_property PULLTYPE PULLUP [get_ports SCL]
set_property PULLTYPE PULLUP [get_ports SDA]





